### PR TITLE
GTK 4

### PR DESCRIPTION
**Pull request by amolenaar**
### PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [X] Chore (refactoring, formatting, local variables, other cleanup)
- [ ] Documentation content changes

### What is the current behavior?

GTK4 is the latest major update to GTK. It has better multi-platform support, as well as better API's for clipboard, DND, etc.

Issue Number: #618 

Depends on: #746 

### What is the new behavior?

Support for GTK4.

I try to keep GTK3 supported. This allows us to merge this PR when it's in good shape and "keeps the shop open".

Packages to pass unit tests:
- [x] gaphor
- [X] gaphor.core
- [x] gaphor.diagram
- [x] gaphor.services
   - [x] copyservice   
- [X] gaphor.plugins
- [X] gaphor.storage
- [x] gaphor.ui
- [x] gaphor.UML
- [x] gaphor.SysML
- [x] gaphor.RAAML
- [x] gaphor.C4Model
- [x] tests

### Does this PR introduce a breaking change?
- [X] Yes
- [ ] No

### Other information

For this PR to be fully functional on macOS, DnD needs to be fixed.

### CODE REVIEW

**Comment by amolenaar** [comment]
@danyeaw I think we can merge this. Maybe after a 2.4.1 release?

**Comment by danyeaw** [comment]
I started to review this tonight, and it looks great so far! Hopefully I can finish the review soon.

**Review by danyeaw — APPROVED** [review]
These changes look superb!

I did try to run it with GTK4 and this is what I'm gettin:
```
(.venv) dan@linux:~/Projects/gaphor> GAPHOR_USE_GTK=4 gaphor
(gaphor:6428): Gtk-WARNING **: 22:03:39.157: Theme parsing error: <data>:1:15-58: Expected ';' at end of block
adding <Gio.SimpleActionGroup object at 0x7f41b7a769c0 (GSimpleActionGroup at 0x1b61fa0)>
done
```

**Comment by amolenaar** [comment]
Yes, currently it starts very slowly in GTK4. I drilled it down to the toolbox and recent files functionality. Both use `Gio.Action`, somehow the "radio button" functionality (one action, multiple target options) makes stuff very slow. 

I was not able to reproduce it is a small example I can share with the GTK folks, though.

**Comment by amolenaar** [comment]
I also found out what caused the _Theme parsing error_.

**Pull request merged**
