### PR TITLE
Copy paste with parent items

### PR DESCRIPTION
**Pull request by amolenaar**
### PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes

### What is the current behavior?

Items, part of a super item, such as Components in a Node, are not copied properly.

Issue Number: #286 

### What is the new behavior?

* When a nested item is copied, it's pasted in the same parent item
* When child and parent item are copied together, a new parent item is created and the child will be part of that

Note that items are still pasted relative to the item position (position to the parent). Gaphor still needs some work so pasted items are always pasted inside the canvas' view port.

### Does this PR introduce a breaking change?
- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by amolenaar** [comment]
It's failing when I update the relationship for UseCase.subject to bi-directional. Other end is `Classifier.useCase`.

**Comment by actionless** [comment]
thanks a lot! now it seems almost perfect, except for some small sporadic padding changes:

2020-05-14--1589461421_1920x1080_scrot

2020-05-14--1589461425_1920x1080_scrot

**Comment by actionless** [comment]
(looks like top and left padding are multiplied by 2)

**Comment by amolenaar** [comment]
Thanks a lot for testing this. I see what’s going on: as part of a paste action, the offset of the elements is changed by 10 pixels. This way it’s clear to a user the new item is pasted. Hoever, it also applies this offset to the nested items. That should not be the case, of course.

**Comment by amolenaar** [comment]
Fixed it in 74c82d4ea53710b7ee27308b84ad39b6445e35e5.

**Comment by actionless** [comment]
i still find it a bit weird what the whole copy-pasted fragment is padded extra 10px, i'd probably would make some sort of dotted line highlight around element, unless you click once somewhere

but that's not a blocker anymore, thanks a lot for your work!

**Pull request merged**
