### PR TITLE
Add Turkish and update French and Russian translations

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Gaphor/Gaphor](https://hosted.weblate.org/projects/gaphor/gaphor/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by danyeaw** [comment]
Hey @sabriunal, are you planning on adding some Turkish translations as well? If so, I can add it to our translation build scripts as well.

**Comment by sabriunal** [comment]
I will begin working on translation soon. I have translated many FOSS software but I have to learn a bit about UML first. I can translate Gaphor UI in a few days.

**Comment by danyeaw** [comment]
@all-contributors please add @BrainKicker for translation

**Comment by danyeaw** [comment]
Thanks @BrainKicker and @Ercalvez for the translation updates!

@sabriunal Thanks for adding the Turkish translation, I'm looking forward to us having Gaphor in that language as well!

**Comment by danyeaw** [comment]
@all-contributors please add @Ercalvez for translation

**Comment by sabriunal** [comment]
@danyeaw Completed: https://github.com/gaphor/gaphor/pull/1977

**Pull request merged**
