### PR TITLE
A Magnet-tool

### PR DESCRIPTION
**Pull request by amolenaar**
### PR Type
What kind of change does this PR introduce?

- [ ] Bug fix
- [x] Feature
- [ ] Chore (refactoring, formatting, local variables, other cleanup)
- [ ] Documentation content changes

### What is the current behavior?

You'll have to select all elements using rubberband selection and move them around.

Issue Number: #1012 

### What is the new behavior?

A simple magnet tool that pulls/pushes all elements on the right/bottom of the bar.

### Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by danyeaw** [comment]
The guides are getting stuck on for me after I use the magnet tool:
image

Should we create a new icon for this instead of the GNOME foot?

**Comment by amolenaar** [comment]
I created a magnet 🧲 this morning. I have to look into the guide lines. Also, if there are no item on the right/bottom the bar is not showing. I think it should. I'm also wondering if the tool can give better visual hints of what's happening. Maybe gray out the left/top side?

**Comment by danyeaw** [comment]
@amolenaar I like the icon! I also noticed that the tool isn't resetting back to the pointer.

**Comment by sz332** [comment]
@danyeaw  Shall it reset back the pointer?

**Comment by danyeaw** [comment]
> @danyeaw  Shall it reset back the pointer?

Yes, I think so, as long as the option to automatically reset is set.

**Comment by amolenaar** [comment]
> > @danyeaw  Shall it reset back the pointer?
> 
> Yes, I think so, as long as the option to automatically reset is set.

I'm not sure how easy that is to do, since the reset functionality is made to trigger when a new item has been created, not after some tool has been executed.

**Comment by amolenaar** [comment]
Okay, tools are reset and the guides are removed after the drop is finished.

**Comment by danyeaw** [comment]
:shipit: Nice job @amolenaar!

**Pull request merged**
