### PR TITLE
Add types for parameters

### PR DESCRIPTION
**Pull request by amolenaar**
### PR Type
What kind of change does this PR introduce?

- [ ] Bug fix
- [x] Feature
- [ ] Chore (refactoring, formatting, local variables, other cleanup)
- [ ] Documentation content changes

### What is the current behavior?

Types cannot be defined on parameter nodes

Issue Number: #2482

### What is the new behavior?

Types are supported.

### Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### Other information

image

@sz332 Should the direction be visible in the diagram as well (similar to `Show Type`)?

Update: direction can be toggled.

### CODE REVIEW

**Comment by sz332** [comment]
@amolenaar I think it would be nice to render a label (in, out, inout, return) before the name, but it could be made in a second PR as well.

**Comment by amolenaar** [comment]
Added a "Show Direction" option. And fixed the type assignment: type should be assigned to the parameter.

**Review by danyeaw — APPROVED** [review]
Nice typed parameters FTW! :shipit:

**Comment by sz332** [comment]
Awesome work!

**Comment by amolenaar** [comment]
Thanks :blush:

**Pull request merged**
