### PR TITLE
Deep copy for packages and diagrams

### PR DESCRIPTION
**Pull request by amolenaar**
### PR Type
What kind of change does this PR introduce?

- [ ] Bug fix
- [x] Feature
- [ ] Chore (refactoring, formatting, local variables, other cleanup)
- [ ] Documentation content changes

### What is the current behavior?

Packages are only copied as is, without content.
Diagrams can be put on a diagram, and they can be copied. However, the contents of the diagram is not copied.

This is especially useful if you copy content between models.

Issue Number: #2422

### What is the new behavior?

* Elements are copied with their owned elements. So if you copy a package and do a full paste, the element and all owned elements are copied.
* Diagrams copy the elements in the diagram. You can now copy a diagram (from a diagram) and full-paste it. This will result in a copy of the diagram
* Update Modeling language docs with the (new) copy/paste interface and did some general improvements as well.

### Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### Other information

Cleaned up the copy and paste interfaces.

Copying is now done via the `copy_full()` function. This function copies the elements, and their owned elements.

NB. Copying is still supposed to happen from diagram to diagram. You cannot copy content in the model browser. This is something we can support in the future, but I deliberately kept it out of scope for this feature.

### CODE REVIEW

**Review by sz332 — APPROVED** [review]
Tested with both class and activity diagrams, copy-paste between models works as expected: creates a copy of all elements as expected.

**Review by danyeaw — APPROVED** [review]
This is a great upgrade to the copy/paste system, nice one @amolenaar!

**Comment by mikekidner** [comment]
@amolenaar / @danyeaw this works great for elements. I noticed that when copying packages, the sub-packages are empty. Also, see how "Existing Package" takes on the name "New Package" in the new model. Not sure what I was expecting, perhaps that ExistingModel becomes a sub package of NewModel.  
 
Screen Shot 2023-07-23 at 8 29 25 am

**Comment by mikekidner** [comment]
In addition, this crash report after closing the above example may be relevant. I closed the new model without saving and then saved the existing model.
```
gaphor.plugins.errorreports.errorreports ERROR Uncaught exception
  + Exception Group Traceback (most recent call last):
  |   File "/Users/mikekidner/BitBucketRepos/gaphor/gaphor/ui/filemanager.py", line 462, in response
  |     handler(answer)
  |   File "/Users/mikekidner/BitBucketRepos/gaphor/gaphor/ui/filemanager.py", line 406, in response
  |     confirm_shutdown()
  |   File "/Users/mikekidner/BitBucketRepos/gaphor/gaphor/ui/filemanager.py", line 387, in confirm_shutdown
  |     self.event_manager.handle(SessionShutdown(self))
  |   File "/Users/mikekidner/BitBucketRepos/gaphor/gaphor/core/eventmanager.py", line 83, in handle
  |     self._events.handle(queue.pop())
  |   File "/Users/mikekidner/BitBucketRepos/gaphor/.venv/lib/python3.11/site-packages/generic/event.py", line 61, in handle
  |     raise ExceptionGroup("Error while handling events", exceptions)
  | ExceptionGroup: Error while handling events (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/Users/mikekidner/BitBucketRepos/gaphor/.venv/lib/python3.11/site-packages/generic/event.py", line 57, in handle
    |     handler(event)
    |   File "/Users/mikekidner/BitBucketRepos/gaphor/gaphor/application.py", line 115, in on_session_shutdown
    |     self.shutdown_session(session)
    |   File "/Users/mikekidner/BitBucketRepos/gaphor/gaphor/application.py", line 143, in shutdown_session
    |     session.shutdown()
    |   File "/Users/mikekidner/BitBucketRepos/gaphor/gaphor/application.py", line 227, in shutdown
    |     self.shutdown_service(name, srv)
    |   File "/Users/mikekidner/BitBucketRepos/gaphor/gaphor/application.py", line 234, in shutdown_service
    |     srv.shutdown()
    |   File "/Users/mikekidner/BitBucketRepos/gaphor/gaphor/core/modeling/elementfactory.py", line 76, in shutdown
    |     self.flush()
    |   File "/Users/mikekidner/BitBucketRepos/gaphor/gaphor/core/modeling/elementfactory.py", line 197, in flush
    |     element.unlink()
    |   File "/Users/mikekidner/BitBucketRepos/gaphor/gaphor/core/modeling/diagram.py", line 327, in unlink
    |     self.connections.remove_connections_to_item(item)
    |   File "/Users/mikekidner/BitBucketRepos/gaphor/.venv/lib/python3.11/site-packages/gaphas/connections.py", line 165, in remove_connections_to_item
    |     disconnect_item(*cinfo)
    |   File "/Users/mikekidner/BitBucketRepos/gaphor/.venv/lib/python3.11/site-packages/gaphas/connections.py", line 148, in _disconnect_item
    |     callback(item, handle, connected, port)
    |   File "/Users/mikekidner/BitBucketRepos/gaphor/gaphor/diagram/_connector.py", line 108, in __call__
    |     adapter.disconnect(handle)
    |   File "/Users/mikekidner/BitBucketRepos/gaphor/gaphor/UML/classes/containmentconnect.py", line 69, in disconnect
    |     oct.subject.package = owner_package(oct.diagram.owner)
    |     ^^^^^^^^^^^^^^^^^^^
    |   File "/Users/mikekidner/BitBucketRepos/gaphor/gaphor/core/modeling/element.py", line 214, in __setattr__
    |     super().__setattr__(key, value)
    |   File "/Users/mikekidner/BitBucketRepos/gaphor/gaphor/core/modeling/properties.py", line 149, in __set__
    |     self.set(obj, value)
    |   File "/Users/mikekidner/BitBucketRepos/gaphor/gaphor/core/modeling/properties.py", line 381, in set
    |     raise TypeError(f"Can not set {obj}.{self.name} to itself")
    | TypeError: Can not set <gaphor.UML.uml.Package element b0d8bd42-2066-11ee-b860-ba28606445aa>.package to itself
    +------------------------------------
gaphor.storage.storage INFO Read 3 elements from file
```

**Comment by mikekidner** [comment]
I couldn't get the crash to happen again. So maybe unrelated.

**Comment by amolenaar** [comment]
Thanks for testing, @mikekidner. I'll have another look at copying to other models.

**Comment by amolenaar** [comment]
It looks like our Hypothesis tests ran into the same issue you experienced: #2536 / https://github.com/gaphor/gaphor/actions/runs/5634866266/job/15265216692.

**Pull request merged**
