### PR TITLE
Swap relationship direction for Generalization, Dependency, Import, Include, and Extend

### PR DESCRIPTION
**Pull request by amolenaar**
### PR Type
What kind of change does this PR introduce?

- [x] Bug fix
- [ ] Feature
- [ ] Chore (refactoring, formatting, local variables, other cleanup)
- [ ] Documentation content changes

### What is the current behavior?

Some relationships are drawn in an unexpected direction. E.g. Generalization is drawn from specific to general type

Issue Number: #929

### What is the new behavior?

Directions have been inverted when drawing. This should feel more natural.

### Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by danyeaw** [comment]
What kind of magic is this to swap directions using the handle_index? 🪄 

If it is OK, I would like to go back through this and compare MagicDraw to this PR and make sure we have them correct.

**Comment by amolenaar** [comment]
No magic. This is a feature already used for all box-line elements. Only I had to swap the handle positions itself to make the initial connect of the "opposite" handle work as expected.

**Comment by danyeaw** [comment]
@amolenaar Should we fix directed associations and then merge this one in as well before we release 2.7.0?

**Comment by amolenaar** [comment]
@danyeaw I would opt to merge this and create a separate PR that changes the orientation of Associations. Associations pop up in a lot of places in the toolbox(es), and we should change all of them.

**Comment by danyeaw** [comment]
Yup, that works!

**Pull request merged**
