### PR TITLE
Remove darkdetect dependency

### PR DESCRIPTION
**Pull request by mathiascode**
libadwaita now follows the system style on Windows and macOS:
- https://gitlab.gnome.org/GNOME/libadwaita/-/merge_requests/492
- https://gitlab.gnome.org/GNOME/libadwaita/-/merge_requests/718

### PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I have read, and I am following the [Contributor guide](https://github.com/gaphor/gaphor/blob/main/CONTRIBUTING.md)
- [x] I have read, and I understand the GNOME [Code of Conduct](https://wiki.gnome.org/Foundation/CodeOfConduct)

### PR Type
What kind of change does this PR introduce?

- [ ] Bug fix
- [ ] Feature
- [x] Chore (refactoring, formatting, local variables, other cleanup)
- [ ] Documentation content changes

### What is the current behavior?

Issue Number: N/A

### What is the new behavior?

No change in behavior. This PR simply removes redundant code.

### Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by danyeaw** [comment]
Thanks so much @mathiascode for the contribution! This is really exciting that libadwaita now supports this directly. Do we know what version this is going into? I tried it on Windows and I didn't have any success.

**Comment by danyeaw** [comment]
Is libadwaita using even-odd versioning, is 1.3 a stable release?

**Comment by mathiascode** [comment]
No, it uses .alpha, .beta, .rc for unstable releases. 1.3 is the latest stable version.
https://blogs.gnome.org/alexm/2023/03/17/libadwaita-1-3/

**Comment by amolenaar** [comment]
Homebrew (macOS) has been updated to install libadwaita 1.3.1.

**Comment by danyeaw** [comment]
As soon as we get https://github.com/wingtk/gvsbuild/pull/903 merged and release a new version of gvsbuild, we should be good to go.

**Comment by amolenaar** [comment]
I (double) checked this PR on macOS and it works fine :+1:.

**Comment by amolenaar** [comment]
@mathiascode Thanks a lot for fixing this.

**Pull request merged**
