### PR TITLE
Add general popup menu for model browser

### PR DESCRIPTION
**Pull request by amolenaar**
### PR Type
What kind of change does this PR introduce?

- [ ] Bug fix
- [x] Feature
- [ ] Chore (refactoring, formatting, local variables, other cleanup)
- [ ] Documentation content changes

### What is the current behavior?

When you cleaned the whole model, there's no way to easily create new top-level packages without putting them in a diagram as well.

Issue Number: #1954

### What is the new behavior?

When no element is selected, you can add top level diagrams and packages.

This allows to add top-level packages and diagrams from anywhere within the model browser (tree view).

You can now deselect the selected element in the model browser with <kbd>Ctrl</kbd>+mouse click.

image

### Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### Other information

I considered adding it to the "create diagram" button in the header bar as well.

* Renamed "tree component" on layout level as `model_browser`, as it's called in the docs.
* Fixed issue where only new popover menu's were created and none were cleaned up
* Remove GTK4 related code from Namespace component.
* Break dependency from tree component/namespace on function in main window module.

### CODE REVIEW

**Review by danyeaw — COMMENTED** [review]
I like being able to right-click and add a new Package. The refactoring you did also is really nice, I like how the GTK4 and GTK3 code is split apart more for this component.

I noticed when I right-click and go to New Diagram, only the Class Diagram is displayed. Was this on purpose? Do we need diagrams that don't exist within any namespace / package?

**Comment by amolenaar** [comment]
> I noticed when I right-click and go to New Diagram, only the Class Diagram is displayed. Was this on purpose? Do we need diagrams that don't exist within any namespace / package?

Somehow the menu is not resizing to contain all diagram types.

**Comment by amolenaar** [comment]
Not sure why the popup menu is not resizing.

Anyway, it may make sense to add all entries in the main menu anyhow:

image

**Comment by danyeaw** [comment]
Thanks @amolenaar, nice improvement!

**Pull request merged**
