### PR TITLE
Fix swimlanes

### PR DESCRIPTION
**Pull request by amolenaar**
### PR Type
What kind of change does this PR introduce?

- [x] Bug fix
- [ ] Feature
- [ ] Chore (refactoring, formatting, local variables, other cleanup)
- [ ] Documentation content changes

### What is the current behavior?

Any item with a Box shape and no children, does not draw.
This goes for Swimlanes (partitions), but also rectangles.

Issue Number: #2988 

### What is the new behavior?

Swimlanes are shown again.

### Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Review by danyeaw — APPROVED** [review]
Great fix @amolenaar!

I'm not sure if this is related to this bug, but shouldn't be make the default size of Swimlanes a bit larger?
image

**Comment by amolenaar** [comment]
That should not be too hard.

**Comment by amolenaar** [comment]
This is also a regression. In 2.22.1 the lanes are wider by default.

**Comment by amolenaar** [comment]
@danyeaw I added some dummy boxes to ensure a minimal width. This broke since empty boxes no longer yield false in if-stamenets, hence the update code of `ElementPresentation` was executed, updating the `min_width` property.

The proper solution is to break it up in shapes, for text and the actual swimlanes. I think we lack a few features there still.

**Pull request merged**
