### PR TITLE
app icon: new diagram metaphor

### PR DESCRIPTION
**Pull request by bertob**
Replace app icon with a new metaphor, as discussed in #506.

image

### PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I have read, and am following the [Contributor guide](https://github.com/gaphor/gaphor/blob/master/CONTRIBUTING.md)
- [x] I have read and understand the [Code of Conduct](https://github.com/gaphor/gaphor/blob/master/CODE_OF_CONDUCT.md)

### PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature (I guess?)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes

### Does this PR introduce a breaking change?
- [ ] Yes
- [ ] No
- [x] Maybe?

I've deleted the small exported versions of the old-style icons, but I didn't add new ones since I'm not sure how they were generated and what they're used for. Feel free to add them back in a followup.

### CODE REVIEW

**Comment by amolenaar** [comment]
I like the direction. This looks a crowded, packed.

I'm wondering. What are typical elements people relate to UML and modeling? Classes, obviously. Use cases, maybe? Sequence diagrams? Would a composition of a couple of those elements work?

**Comment by danyeaw** [comment]
I think Class, Use Case, and Activity would be the big 3. I really like this logo, but I do agree that it is a little busy. @bertob Do you have any ideas on simplifying it just a little bit?

**Comment by bertob** [comment]
My feeling is we need at least 3 boxes to get the idea of UML across, 2 boxes with arrows look like some kind of generic flow/transformation process. I could try dropping some of the arrows maybe.

**Comment by amolenaar** [comment]
@bertob Thanks. I agree that icon should be something UML'ish. If removing some arrows works, that would be really nice. Hopefully it will make it look simpler :smiley:.

**Comment by bertob** [comment]
Tried removing a few things, but it's really tricky. This is a tiny bit simpler:

image

**Comment by danyeaw** [comment]
@all-contributors please add @bertob for design

**Comment by danyeaw** [comment]
@bertob I like this more simple version, would you mind please updating your PR?

We also have other icons that we need to update:
1. `gaphor/service/helpservice/org.gaphor.Gaphor.svg`
2. `macos-dmg/iconset/*png` updatable by running `make all`
3. `win-installer/misc/gaphor.ico` updatable by running `build-ico.sh` in the same directory
4. https://github.com/flathub/org.gaphor.Gaphor/tree/master/logos

I am glad to help out getting the others updated.

**Comment by amolenaar** [comment]
It's a small change, but it looks more balanced already. :+1:

Does it work when the top-left and center lines are also removed? (just curious)

**Comment by bertob** [comment]
Super quick experiments:

image

image

I don't think this works, i think we need a certain feeling of complexity to get the UML idea across unfortunately. Otherwise it starts looking like a generic diagram app again.

**Comment by bertob** [comment]
@danyeaw updated the MR with the simplified version

**Comment by danyeaw** [comment]
Thanks @bertob!

**Comment by danyeaw** [comment]
@bertob Thanks again for your contribution, the new logo looks great! :tada:

**Pull request merged**
