### PR TITLE
Clean up Toolbox

### PR DESCRIPTION
**Pull request by amolenaar**
### PR Type
What kind of change does this PR introduce?

- [ ] Bug fix
- [ ] Feature
- [x] Chore (refactoring, formatting, local variables, other cleanup)
- [ ] Documentation content changes

### What is the current behavior?

Clicking on a tool twice deselects it.

### What is the new behavior?

Selection is handled by Gtk.FlowBox. It allows us to better style the toolbox as well.

### Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### Other information

image

### CODE REVIEW

**Comment by danyeaw** [comment]
@amolenaar Did you want to rebase this?

**Comment by amolenaar** [comment]
Will do

**Comment by amolenaar** [comment]
@danyeaw Done

**Review by danyeaw — APPROVED** [review]
Nice, I like how the new selected tool looks in blue :+1:

**Pull request merged**
