### PR TITLE
Hungarian translation updates

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://hosted.weblate.org/projects/gaphor/gaphor/) for Gaphor/Gaphor.

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by danyeaw — APPROVED** [review]
Thanks for the translation updates @ovari!

**Comment by ovari** [comment]
You are welcome! Can you please release a version with 100% Hungarian translations to Flathub? Thank you

**Comment by danyeaw** [comment]
@ovari let's close some of the other issues you raised regarding translations prior to releasing a new version. A version release requires quite a few steps. If you want to test out the latest changes, setting up a development environment would be ideal.

**Comment by ovari** [comment]
Okay, if the other fixes are simple, please do so before a version release. If you can please also as the last step before a version release update the Weblate translations that would be appreciated. Thank you

**Pull request merged**
