### PR TITLE
Presentation class inherits directly from Base

### PR DESCRIPTION
**Pull request by amolenaar**
This PR builds on #3541.

### PR Type
What kind of change does this PR introduce?

- [ ] Bug fix
- [ ] Feature
- [x] Chore (refactoring, formatting, local variables, other cleanup)
- [ ] Documentation content changes

### What is the current behavior?

`Presentation` inherited from `Element`, which provided it with features it would never need, such as a name, ownership.

Issue Number: N/A

### What is the new behavior?

`Presentation` is now derived directly from `Base`. This makes it clear that this kind of element is different from the modeling language base type `Element`.

### Does this PR introduce a breaking change?
- [x] Yes
- [ ] No

### Other information

* Documentation improvements

### CODE REVIEW

**Review by danyeaw — APPROVED** [review]
Thanks @amolenaar!

**Comment by amolenaar** [comment]
@danyeaw I still have to adress your comments in #3531.

**Comment by danyeaw** [comment]
@amolenaar Whoops, did I merge these out of order?

**Comment by amolenaar** [comment]
No, they're now part of that pr. I addressed your comments and fixed the merge conflict. It should be good to go, now.

**Pull request merged**
