### PR TITLE
Scale parameters to contain all text

### PR DESCRIPTION
**Pull request by amolenaar**
### PR Type
What kind of change does this PR introduce?

- [x] Bug fix
- [ ] Feature
- [ ] Chore (refactoring, formatting, local variables, other cleanup)
- [ ] Documentation content changes

### What is the current behavior?

Parameters with long names get out of the box

Issue Number: #2429 

### What is the new behavior?

Parameter text remains inside the box.

image

### Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Review by danyeaw — APPROVED** [review]
Nice fix!

**Comment by danyeaw** [comment]
Do you want to add a changelog entry for this, and we'll include it with 1.19.2?

**Comment by amolenaar** [comment]
Sure.

**Comment by amolenaar** [comment]
1 min, I'm facing an issue with this code.

**Pull request merged**
