### PR TITLE
Improve Packaging and Sign / Notarize macOS App

### PR DESCRIPTION
**Pull request by danyeaw**
- Makes packaging more common between Windows and macOS using PyInstaller.
- Signs and notarizes the .app and .dmg.

### PR Checklist
Please check if your PR fulfills the following requirements:

- [X] I have read, and am following the [Contributor guide](https://github.com/gaphor/gaphor/blob/master/CONTRIBUTING.md)
- [X] I have read and understand the [Code of Conduct](https://github.com/gaphor/gaphor/blob/master/CODE_OF_CONDUCT.md)

### PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes

### What is the current behavior?
macOS apps aren't signed and create warnings that the app isn't trusted

Issue Number: #395 

### What is the new behavior?
macOS app is signed an notarized using an Apple Developer account.

### Does this PR introduce a breaking change?
- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by amolenaar** [comment]
I like the idea to unify the builds. I was thinking of moving to py2app.
If we can do the same with pyInstaller, that would be really nice. the macOS build has required a fair amount of maintenance.
Also, with macOS being arder to built for, with all their lock down measures we're probably better of to share that burden with the pyinstaller community ;). 

BTW. `gaphor/ui/macosshim.py` should not be removed. It allows macOS file and quit events to be nicely handled by Gaphor. It's bridging `NSApplication` and `Gtk.Application`.

**Comment by danyeaw** [comment]
@amolenaar When I have the macosshim in, I am getting:
```
TypeError: <GtkosxApplication.Application object at 0x112573bc0 (GError at 0x7fa8061d7420)>: unknown signal name: NSApplicationOpenFile
```
when launching Gaphor. If I remove the shim everything works fine.

**Comment by danyeaw** [comment]
@amolenaar I resolved the issue by adding hooks for GtkosxApplication, I'll work on getting them pushed upstream as well. I think this is ready to go, I'll add the app signing as a separate PR.

**Comment by amolenaar** [comment]
> @amolenaar When I have the macosshim in, I am getting:
> 
> ```
> TypeError: <GtkosxApplication.Application object at 0x112573bc0 (GError at 0x7fa8061d7420)>: unknown signal name: NSApplicationOpenFile
> ```
> 
> when launching Gaphor. If I remove the shim everything works fine.

This shim should only be activated on macos. What os are you running on?

**Comment by danyeaw** [comment]
> > @amolenaar When I have the macosshim in, I am getting:
> > ```
> > TypeError: <GtkosxApplication.Application object at 0x112573bc0 (GError at 0x7fa8061d7420)>: unknown signal name: NSApplicationOpenFile
> > ```
> > 
> > 
> > when launching Gaphor. If I remove the shim everything works fine.
> 
> This shim should only be activated on macos. What os are you running on?

@amolenaar I was getting the error in macOS, but I fixed it by adding a PyInstaller hook.

**Comment by danyeaw** [comment]
> Note that a location where code is expected to reside cannot generally contain directories full of nested code, because those directories tend to be interpreted as bundles. So this occasional practice is not recommended and not officially supported. If you do do this, do not use periods in the directory names. The code signing machinery interprets directories with periods in their names as code bundles and will reject them if they don't conform to the expected code bundle layout.

To get around the code signing treating it as a code bundle, I am trying to move the `Gaphor.app/Contents/MacOS/lib/gdk-pixbuf-2.0` folder to `Gaphor.app/Contents/Resources/lib` and then symlink it back to the MacOS folder. I simplified this greatly and put it in the build script, however, I am getting Failed to load icon errors.

The only difference between the working Gaphor.app and the updated one, is now there is an extra loaders directory in `Gaphor.app/Contents/MacOS/lib/gdk-pixbuf-2.0/2.10.0` since now it links to the Resources directory.

**Comment by amolenaar** [comment]
I'm not sure if an app bundle should have symlinks. Normally I would expect such code in the `Resources` folder, as is done for Inkscape and GIMP.
I assume we can not tweak PyInstaller to do so.

The gdk-pixbuf folder can be defined by setting an environment variable, maybe that helps?

What's the source of the text you're quoting?

**Comment by danyeaw** [comment]
> I'm not sure if an app bundle should have symlinks. Normally I would expect such code in the `Resources` folder, as is done for Inkscape and GIMP.

I agree, ideally we can find a fix that eventually doesn't use symlinks.

> I assume we can not tweak PyInstaller to do so.

I am sure we can always submit a PR improve this, but I don't think there exists a setting currently.

> The gdk-pixbuf folder can be defined by setting an environment variable, maybe that helps?

This is a great tip, I didn't know about this. :+1: 

> What's the source of the text you're quoting?

I got it from a [recipe to code sign a QT PyInstaller app](https://github.com/pyinstaller/pyinstaller/wiki/Recipe-OSX-Code-Signing-Qt). The original source is the [macOS Code Signing in Depth](https://developer.apple.com/library/archive/technotes/tn2206/_index.html#//apple_ref/doc/uid/DTS40007919-CH1-TNTAG201) Apple Developer doc.

**Comment by danyeaw** [comment]
I think we should keep our current macos build scripts until we can fix these issues with PyInstaller. I am going to close the PR, but keep the branch and open a new PR to sign and notarize using our current build scripts.

**Comment by danyeaw** [comment]
I have submitted https://github.com/pyinstaller/pyinstaller/pull/5435 to resolve the issue with gdk-pixbuf library locations causing signing to fail.

**Comment by danyeaw** [comment]
```
(.venv) danielyeaw@Daniels-MacBook-Pro /Applications % codesign -dv --verbose=4 Gaphor.app
Executable=/Applications/Gaphor.app/Contents/MacOS/gaphor-exe
Identifier=org.gaphor.gaphor
Format=app bundle with Mach-O thin (x86_64)
CodeDirectory v=20500 size=21565 flags=0x10000(runtime) hashes=665+5 location=embedded
VersionPlatform=1
VersionMin=657152
VersionSDK=658176
Hash type=sha256 size=32
CandidateCDHash sha1=56009b2cb90c78924a4d7ca805d1cc7daefbb680
CandidateCDHashFull sha1=56009b2cb90c78924a4d7ca805d1cc7daefbb680
CandidateCDHash sha256=141f0370a0c857cc77e9562e7e731d897e12b9e4
CandidateCDHashFull sha256=141f0370a0c857cc77e9562e7e731d897e12b9e445e1b224cbe200c6625191b0
Hash choices=sha1,sha256
CMSDigest=67015ada54db56371d5adbf58b0c05569328a54864cd2a7f5f4ae1c990c77093
CMSDigestType=2
Page size=4096
CDHash=141f0370a0c857cc77e9562e7e731d897e12b9e4
Signature size=9052
Authority=Developer ID Application: Daniel Yeaw (Z7V37BLNR9)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=Jan 2, 2021 at 4:00:55 PM
Info.plist entries=9
TeamIdentifier=Z7V37BLNR9
Runtime Version=10.11.0
Sealed Resources version=2 rules=13 files=6748
Internal requirements count=1 size=180
```
Screen Shot 2021-01-02 at 4 18 22 PM

System Information:
Gaphor:

  Version:	0.0.0
  Obtained from:	Identified Developer
  Last Modified:	1/2/21, 4:00 PM
  Signed by:	Developer ID Application: Daniel Yeaw (Z7V37BLNR9), Developer ID Certification Authority, Apple Root CA
  Location:	/Applications/Gaphor.app
  Kind:	64-bit

Gaphor.app is signed and notarized. It looks like I need to fix the Version info.

**Comment by amolenaar** [comment]
Sweet! It finally worked.

How should this work for a release then? Should we submit the release build to Apple?

**Comment by danyeaw** [comment]
Woot! :smile:

Right now it is submitting all builds to Apple, so I get an email for successful notarization 2x each build (one for the app and one for the dmg). We could make it for release only, the only risk of that is that if it breaks we wouldn't know until it is time to release.

**Comment by danyeaw** [comment]
@amolenaar My PyInstaller PR was merged, anything else needed before we merge this?

**Comment by danyeaw** [comment]
@amolenaar PyInstaller 4.2 is now out with the fixes, I think this is ready to go as long as you are aligned with using PyInstaller. :+1:

**Comment by amolenaar** [comment]
I'm perfectly fine with PyInstaller. Our own script proved to require quite a bit of maintenance. I hope the maintenance costs for using PyInstaller are lower.

Well done!

**Pull request merged**
