### PR TITLE
Update translation for docs.gaphor.org

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Gaphor/docs.gaphor.org](https://hosted.weblate.org/projects/gaphor/docs-gaphor-org/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by danyeaw — APPROVED** [review]

**Comment by danyeaw** [comment]
Thanks @stansz84 and @ovari! You rock ❤️

**Comment by stansz84** [comment]
Unable to merge repository. 

_Rebasing (1/3)
_dropping 3406a4ff9da981819f9a52f5818dabb43181a41d Update Hungarian translation for docs.gaphor.org -- patch _contents already upstream
_Rebasing (2/3)
_Auto-merging docs/locale/fr/LC_MESSAGES/docs.po
_CONFLICT (content): Merge conflict in docs/locale/fr/LC_MESSAGES/docs.po
_error: could not apply 82f3f8479... Update French translation for docs.gaphor.org
_hint: Resolve all conflicts manually, mark them as resolved with
_hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
_hint: You can instead skip this commit: run "git rebase --skip".
_hint: To abort and get back to the state before "git rebase", run "git rebase --abort"._

I'm sorry but I don't know what to do ?
Could not apply 82f3f8479... Update French translation for docs.gaphor.org_

**Comment by stansz84** [comment]
I'm not working directly in GIT, I'm using WEBLATE. The https://hosted.weblate.org/projects/gaphor/docs-gaphor-org/ page is locked with a warning that displays the previous message. It's impossible to continue translating.

**Comment by amolenaar** [comment]
@danyeaw I fixed the merge conflict, but I cannot unlock the tranmslation repo. the wlc tool tells me I do not have permission to perform that action.

**Comment by amolenaar** [comment]
Hi @stansz84, sorry it took so long. The merge conflict has been resolved and weblate allows for translating the docs again.

**Pull request merged**
