### PR TITLE
Fix decision node loading

### PR DESCRIPTION
**Pull request by amolenaar**
### PR Type
What kind of change does this PR introduce?

- [x] Bug fix
- [ ] Feature
- [ ] Chore (refactoring, formatting, local variables, other cleanup)
- [ ] Documentation content changes

### What is the current behavior?

Models can not load if "show-type" is selected on decision nodes.

Issue Number: #2325 

### What is the new behavior?

* Fix loading of decision nodes with "show-type" enabled
* Add extra test to validate properties on all diagram items.

### Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Review by danyeaw — APPROVED** [review]
This looks really good, nice fix!

This is kind of a nit, but underlaying isn't a word, but underlying is. Would this be an opportunity to rename this to show_underlying_type?

**Comment by amolenaar** [comment]
@danyeaw Thanks for correcting this. For sure this is *the* opportunity to fix it once and for all.

**Comment by Fell-x27** [comment]
Additionally, I suggest that if the utility encounters an unknown node or subnode in the XML, it should just ignore it, write a relevant message to the log, and continue operating, instead of crashing.

**Comment by amolenaar** [comment]
> Additionally, I suggest that if the utility encounters an unknown node or subnode in the XML, it should just ignore it, write a relevant message to the log, and continue operating, instead of crashing.

Doing so has the potential side effect of loading a completely invalid model. However, in this case it would've helped a lot as well.

It can be done, but Gaphor should make it really clear to users that something is not okay.

**Pull request merged**
