### PR TITLE
#1310 Update to Readme.md - Greeter dialog and new diagram button usage

### PR DESCRIPTION
**Pull request by Texopolis**
### PR Checklist
Please check if your PR fulfills the following requirements:

- [X] I have read, and I am following the [Contributor guide](https://github.com/gaphor/gaphor/blob/master/CONTRIBUTING.md)
- [X] I have read, and I understand the [Code of Conduct](https://github.com/gaphor/gaphor/blob/master/CODE_OF_CONDUCT.md)

### PR Type
What kind of change does this PR introduce?

- [ ] Bug fix
- [ ] Feature
- [ ] Chore (refactoring, formatting, local variables, other cleanup)
- [X] Documentation content changes

### What is the current behavior?

The current readme.md states only one diagram is available and opens automatically. This change to the readme informs users there are multiple diagrams available depending on the model selected and a button is implemented to add diagrams
Issue Number: #1310 

### Does this PR introduce a breaking change?
- [ ] Yes
- [X] No

### CODE REVIEW

**Review by danyeaw — APPROVED** [review]
Thanks @Texopolis, this looks great!

I cleaned things up a bit of the formatting to wrap the lines at 80 characters and added on a few changes to how paste is now working :+1: 

Thanks for your contribution :yellow_heart:

**Comment by danyeaw** [comment]
@all-contributors please add @Texopolis for doc

**Comment by Texopolis** [comment]
@danyeaw thank you for your patience and help by making this process so much less intimidating! I hope there's other contributions I can participate with in the future!

**Comment by danyeaw** [comment]
@Texopolis We would be glad to have future contributions, thanks again!

**Pull request merged**
