### PR TITLE
Focus already opened model

### PR DESCRIPTION
**Pull request by amolenaar**
### PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes

### What is the current behavior?

If an already opened model is opened again, it's loaded in a new window.

Issue Number: #482

### What is the new behavior?

When an already opened model is "opened", the window is focused.

### Notes

* `gaphor.ui.event.FileLoaded/Saved` have been replaced by `gaphor.event.ModelLoaded/Saved`

### CODE REVIEW

**Review by danyeaw — COMMENTED** [review]
This implementation looks really good!

Since the app is a singleton, I am concerned about not allowing someone to open a model twice. I think there are some use cases where you would want to be able to reference a diagram while viewing another diagram in the same model.

Is the use case here that the user doesn't know they already have the model open or do they know they have it open and they are using the open menu to switch projects?

Do we want to at least add an option to the open menu or a popup dialog to allow a user to open the model in a new window if they need to?

**Comment by amolenaar** [comment]
> Since the app is a singleton, I am concerned about not allowing someone to open a model twice. I think there are some use cases where you would want to be able to reference a diagram while viewing another diagram in the same model.

This can also lead to strange situations, where both instances of the same model are changed differently. 

This could also be resolved by allowing users to detach diagrams from the notebook view, or open it in a second notebook, next to the active one, like one can do with files in VSCode (ctrl-click).

> Is the use case here that the user doesn't know they already have the model open or do they know they have it open and they are using the open menu to switch projects?

They could also use the file explorer.

> Do we want to at least add an option to the open menu or a popup dialog to allow a user to open the model in a new window if they need to?

We can do this if the user explicitly opens the model though te open menu. If it's "opened" by double clicking a model file in their file manager, I suppose it's better to just show the already opened model instead. That's the behavior I see with text editors at least ;).

**Comment by danyeaw** [comment]
> This could also be resolved by allowing users to detach diagrams from the notebook view, or open it in a second notebook, next to the active one, like one can do with files in VSCode (ctrl-click).

Yup, I agree.

> They could also use the file explorer.

Ahh yes, I hadn't thought about that use case.

> We can do this if the user explicitly opens the model though te open menu. If it's "opened" by double clicking a model file in their file manager, I suppose it's better to just show the already opened model instead. That's the behavior I see with text editors at least ;).

That's a good idea, I like that!

**Comment by amolenaar** [comment]
@danyeaw I added a little dialog if a user wants to open an already opened model.

I'm not really happy with the phrasing: the buttons should be more descriptive than "Yes"/"No", but that's something I want to flesh out separately, since that means all question dialogs do need an update.

**Review by danyeaw — APPROVED** [review]
I really like this, nice one! :stars:

**Pull request merged**
