### PR TITLE
Add Support for Containment Relationship

### PR DESCRIPTION
**Pull request by danyeaw**
Signed-off-by: Dan Yeaw <dan@yeaw.me>

This PR adds support for the containment relationship with UML/SysML.

### PR Checklist
Please check if your PR fulfills the following requirements:

- [X] I have read, and am following the [Contributor guide](https://github.com/gaphor/gaphor/blob/master/CONTRIBUTING.md)
- [X] I have read and understand the [Code of Conduct](https://github.com/gaphor/gaphor/blob/master/CODE_OF_CONDUCT.md)

### PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes

### What is the current behavior?
It is possible to nest objects under a package, but the containment relationship is not supported.

Issue Number: #690 

### What is the new behavior?
Support for the containment relationship for those elements that can currently be nested.

### Does this PR introduce a breaking change?
- [ ] Yes
- [X] No

### TODO

- [x] Containment relationship works to nest packages
- [x] Containment relationship allows nesting of other currently nestable elements

### CODE REVIEW

**Comment by danyeaw** [comment]
There isn't a containment relationship in UML, instead, the relationship in the diagram represents a `UML.Package.ownedElement`. I think this is similar to how a CommentLine represents an association but it isn't a unique element itself.

@amolenaar If you have a min to look at this, I must be doing something silly because when I run Gaphor in a debugger `ContainmentConnect` `allow()` method isn't being called when I create a new ContainmentItem.

**Comment by amolenaar** [comment]
@danyeaw Shouldn't the containment relationship be in the SysML profile? I can see no reference of it in the UML specs.

**Comment by danyeaw** [comment]
@amolenaar I don't think the UML spec actually uses the term containment, but it is shown in the spec. Here is section 12.2.5 where it shows the notation for a package:
image

I have seen it called the Containment relationship in most of the tools and books. This is from UML 2 and the Unified Process book:
image

**Comment by amolenaar** [comment]
Indeed. It's referred to as "ownership notation". :smiley: 

I think it's working. I added a little behavior for the disconnect action as well. When disconnected, it moves the item to the same namespace as the diagram. Is this what you expect?

**Comment by danyeaw** [comment]
Thanks again for your help with this @amolenaar! I think I was stuck because I was missing `containmentconnect.py` from the `__init__.py`, I knew it had to be something silly like that :sweat_smile:.

**Comment by amolenaar** [comment]
Is it good to merge now? Or are there features missing still?

**Pull request merged**
