### PR TITLE
Fix about dialog logo

### PR DESCRIPTION
**Pull request by amolenaar**
### PR Type
What kind of change does this PR introduce?

- [X] Bug fix
- [ ] Feature
- [ ] Chore (refactoring, formatting, local variables, other cleanup)
- [ ] Documentation content changes

### What is the current behavior?

About dialog does not show the icon

### What is the new behavior?

Logo has been moved to the icon theme, so it can be picked up by the about dialog again.

### CODE REVIEW

**Comment by danyeaw** [comment]
@amolenaar Should we run the full build on this?

**Comment by ovari** [comment]
@danyeaw @amolenaar can https://github.com/gaphor/gaphor/issues/1044, https://github.com/gaphor/gaphor/issues/1045, https://github.com/gaphor/gaphor/issues/1046 please be fixed before a full build so that we can properly test?

Thank you

**Review by danyeaw — APPROVED** [review]
Nice fix @amolenaar!

**Comment by danyeaw** [comment]
> @danyeaw @amolenaar can #1044, #1045, #1046 please be fixed before a full build so that we can properly test?

@ovari I meant a full build for testing, I didn't mean release a new version.

**Pull request merged**
