### PR TITLE
Fix "rename" from popover

### PR DESCRIPTION
**Pull request by amolenaar**
### PR Type
What kind of change does this PR introduce?

- [x] Bug fix
- [ ] Feature
- [ ] Chore (refactoring, formatting, local variables, other cleanup)
- [ ] Documentation content changes

### What is the current behavior?

When you select the "Rename" entry from the popover menu in the tree view, the text is not editable on Wayland.

On X11 it works fine, though :/.

### What is the new behavior?

"Rename" is available fro a shortcut (`F2`). I could not find a way to make the popover work in combination with the edit feature.
Therefore I propose to remove the "Rename" option from the popover.

### CODE REVIEW

**Comment by danyeaw** [comment]
@amolenaar Do you think this is the only option? I rather liked rename being in the right click menu.

**Comment by amolenaar** [comment]
@danyeaw It's a bit weird. It looks like focus is (temporary) changing when the popup is removed. Something that does not happen on X11.

But now that you mention it, maybe it works if I delay editing by some time, say 200ms.

**Comment by amolenaar** [comment]
@danyeaw I think you're gonna like those changes.

**Comment by danyeaw** [comment]
That is working much better for me :+1: 

One thing that I noticed which seems somewhat inconsistent on how we do rename:
1. If you rename from a diagram, hitting Escape undoes the editing and hitting enter accepts it
2. If you rename from the tree view, hitting Escape accepts the edit, and hitting enter creates another copy of the element on the diagram.

I think this could be pretty unexpected for a user. What do you think?

**Review by danyeaw — APPROVED** [review]

**Comment by amolenaar** [comment]
This is indeed some unexpected behavior. It should just exit, and escape should cancel the edit.

**Comment by amolenaar** [comment]
I addressed the issue with editing. I forgot to provide a proper return value if the key (enter/escape) was handled.

**Comment by danyeaw** [comment]
Thanks @amolenaar, that is much better!

**Pull request merged**
