### PR TITLE
Rename usage of Partitions to Swimlanes

### PR DESCRIPTION
**Pull request by amolenaar**
### PR Type
What kind of change does this PR introduce?

- [ ] Bug fix
- [ ] Feature
- [X] Chore (refactoring, formatting, local variables, other cleanup)
- [ ] Documentation content changes

### What is the current behavior?

Swimlanes are called partition. Although the model element is called partition, it's representation is called a swimlane.

Issue Number: #1003 

### What is the new behavior?

Swimlanes are called swimlanes.

* Fixed the icon for swimlanes in the tree view.
* Fixed icon rendering. By explicitly settng the full color, we so not need to translate strokes to paths.

image

### Does this PR introduce a breaking change?
- [X] Yes
- [ ] No

### CODE REVIEW

**Comment by sz332** [comment]
Some possible bugs I found:

- When adding a new partition, the name is NewActivityPartition, I think it should be NewSwimlane
- In the tree on the left side, when adding a new partition, it will be added at the beginning of the list
- The Name field in the properties tab is totally confusing (what does it actually change???), would be best not to be displayed

If not possible to hide, then the following bug shall be fixed:

 - Create a swimlane 
 - Delete the name of the swimlane
 - The partition name does not change, however on the model tree, it changes together with the text
 - Causing confusions like that:
 
image

**Comment by amolenaar** [comment]
@sz332 Thanks for testing. I'll address the issues.

The tree view is sorted on name, hence the place.

**Comment by sz332** [comment]
@amolenaar tested the change, looks great, well done!

**Review by danyeaw — APPROVED** [review]
LGTM! :+1:

**Pull request merged**
