### PR TITLE
Adding instructions for anaconda install

### PR DESCRIPTION
**Pull request by hulsed**
Adding docs page for installing anaconda within anaconda per our discussion here: https://github.com/gaphor/gaphor/issues/2821. It may require some nudging to fit within the rest of the documentation, but I've verified the process on an otherwise blank windows machine (perhaps this should be titled as windows-only? I am not sure how ).

- Docs page added for anaconda installation
- See: #2821

### PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I have read, and I am following the [Contributor guide](https://github.com/gaphor/gaphor/blob/main/CONTRIBUTING.md)
- [x] I have read, and I understand the GNOME [Code of Conduct](https://conduct.gnome.org/)

### PR Type
What kind of change does this PR introduce?

- [ ] Bug fix
- [ ] Feature
- [ ] Chore (refactoring, formatting, local variables, other cleanup)
- [x] Documentation content changes

### What is the current behavior?

Currently, it's difficult to work with gaphor from an external python console without a full development install which may require root permissions. This provides instructions for installing gaphor in an anaconda environment so can install and work with gaphor modules without root permissions.

Issue Number: #2821

### What is the new behavior?
This commit adds instructions for working in an anaconda environment.

### Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by danyeaw** [comment]
Hi @hulsed, thanks so much for the contribution! If libadwaita and gtksourceview5 aren't available with anaconda what is the result of this environment? Are able to successfully install Gaphor and run scripts, but not able to launch Gaphor itself?

**Comment by hulsed** [comment]
@danyeaw I added some language here that I hope explains that better. Unfortunately, I haven't really been able to demo this extensively to see what I can/can't do, but I can say:
- it lets you interact with some gaphor classes like SysML, ElementFactory, and ModelingLanguageService
- interacting with Session does not work, ostensibly because it wants gtk inspection. The error it gives is:
image

I'd like to characterize what you can and can't do here a bit better, but unfortunately--if I get a bit further working with this, perhaps I could perform some tests/searches and make a list or diagram?

**Review by danyeaw — APPROVED** [review]
Thanks so much for the contribution @hulsed! I think over time we can figure out if using Anaconda or some other solution is best for your use case, but I think adding some initial docs for the Anaconda crowd is great :+1:. Maybe we need to work to get libadwaita and gtksourceview packaged.

**Comment by danyeaw** [comment]
@all-contributors please add @hulsed for docs

**Pull request merged**
