### PR TITLE
Make SysML Enumerations also ValueTypes

### PR DESCRIPTION
**Pull request by amolenaar**
### PR Type
What kind of change does this PR introduce?

- [ ] Bug fix
- [x] Feature
- [ ] Chore (refactoring, formatting, local variables, other cleanup)
- [ ] Documentation content changes

### What is the current behavior?

UML's Enumeration is made available in the SysML profile. However, Enumeration is not really supported. It should be a ValueType.

Issue Number: #1485

### What is the new behavior?

When you create an enumeration with the SysML profile selected, it displays a ValueType stereotype to the Enumeration.

### CODE REVIEW

**Comment by danyeaw** [comment]
In other tools there is still an Enumeration object for SysML in the toolbar, it just applies a valueType stereotype to the enumeration when you create it. I don't think we want to get rid of the ability to create an Enumeration.

**Comment by amolenaar** [comment]
Now added an attribute to Enumeration. It will either show with UML or SysML profile, depending if you take the enum from the UML or SysML profile.

image

There's no switch in the property editor, on purpose.

**Comment by danyeaw** [comment]
This PR doesn't remove the Enumeration from the SysML Blocks toolbox now, right? For some reason, I can't get it to show up, I even created a new virtualenv.

image

**Review by danyeaw — APPROVED** [review]
This is a great solution @amolenaar :+1:

**Pull request merged**
