### PR TITLE
Add Codespaces Configuration

### PR DESCRIPTION
**Pull request by danyeaw**
This PR sets up codespaces to setup a Gaphor dev environment in a couple of clicks in the browser or in VSCode.

### PR Checklist
Please check if your PR fulfills the following requirements:

- [X] I have read, and I am following the [Contributor guide](https://github.com/gaphor/gaphor/blob/main/CONTRIBUTING.md)
- [X] I have read, and I understand the [Code of Conduct](https://github.com/gaphor/gaphor/blob/main/CODE_OF_CONDUCT.md)

### PR Type
What kind of change does this PR introduce?

- [ ] Bug fix
- [X] Feature
- [ ] Chore (refactoring, formatting, local variables, other cleanup)
- [ ] Documentation content changes

### What is the current behavior?
If you launch codespaces it uses a default configuration.

Issue Number: N/A

### What is the new behavior?
Codespaces has the Gaphor dependencies and other dev environment configs.

### Does this PR introduce a breaking change?
- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by amolenaar** [comment]
Having a devcontainer config is a safe option.

How does CodeSpaces work? Do I have to sign up or something?

Since this is a GUI app, does it make sense to have a code space? I mean: can you run it?

**Comment by danyeaw** [comment]
You can sign up for the beta at https://github.com/features/codespaces/signup

I have it setup to launch a flexbox GUI, so you can interact with Gaphor using your web browser or with VNC.

I don't think it will completely replace a local dev environment, but I think it is still very useful to be able to contribute from any computer with a web browser, especially for a smallish PR.

**Review by amolenaar — APPROVED** [review]
I like this.

Does the environment also work locally? With Wayland? I have some trouble loading the devcontainer environment, but that's a local SELinux thing, I guess.

**Comment by danyeaw** [comment]
Yup, with Codespaces you can tell it to launch locally. I have openSUSE MicroOS with VSCode installed via Flatpak, and it works really well.

**Pull request merged**
