### PR TITLE
Associate Action with right Partition

### LINKED ISSUE #3050: First activity partition gets all the nodes
### Describe the bug
When querying activity partitions and seeing what nodes under which partition is, it was discovered that the first partition in the set gets all the nodes and all the rest are empty.

### To Reproduce
1. Create the following activity diagram
image
2. Open console and write
```
from gaphor.UML import uml
[f'{p.name}: {[n.name for n in p.node]}' for p in select(uml.ActivityPartition)]
```
3. See that the output is: `["Swimlane One: ['A1', 'A2']", 'New Swimlane: []']`

### Expected behavior

Expected output of the steps should be `["Swimlane One: ['A1']", "New Swimlane: ['A2']"]`

### OS
- [x] Linux (Mint)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.23.2

### PR DESCRIPTION
**Pull request by amolenaar**
### PR Type
What kind of change does this PR introduce?

- [x] Bug fix
- [ ] Feature
- [ ] Chore (refactoring, formatting, local variables, other cleanup)
- [ ] Documentation content changes

### What is the current behavior?

Actions are always assigned to the first partition when dragging.

Issue Number: fixes #3050

### What is the new behavior?

The partition below the mouse cursor is now found.

### Other information

* Add a bit of extra typing to the core collection class.
* Added tests for State machine dropzone behavior.

### CODE REVIEW

**Review by danyeaw — COMMENTED** [review]
Hi @amolenaar, these changes look good. I gave it a spin and for me the first drop is still being associated with the first swimlane even if I drop it on the 2nd. When I select the action and release it, then it is associated with the 2nd one.

**Comment by amolenaar** [comment]
Ah, I only fixed it for moving actions from one partition to the other. I'll have a look at the `drop()` logic.

**Comment by danyeaw** [comment]
Hi @amolenaar, I was dropping from the toolbox since I thought that would be the primary use case.

**Comment by amolenaar** [comment]
I extended the use of `drop()` to also support dropping items on other items in a diagram. This simplifies the code, I think, since we only need one concept (drop) to handle items being placed on top of one another.

**Comment by danyeaw** [comment]
@amolenaar Oh nice one! I haven't had a chance to look at the updates yet, but I should be able to make some time tomorrow to do one last review.

**Review by danyeaw — APPROVED** [review]
Really nice update to the drop zones @amolenaar!

**Pull request merged**
