### PR TITLE
Update Gvsbuild to version 2024.1.0

### PR DESCRIPTION
**Pull request by danyeaw**
GTK 4.12.5 and friends on Windows.

### PR Checklist
Please check if your PR fulfills the following requirements:

- [X] I have read, and I am following the [Contributor guide](https://github.com/gaphor/gaphor/blob/main/CONTRIBUTING.md)
- [X] I have read, and I understand the GNOME [Code of Conduct](https://wiki.gnome.org/Foundation/CodeOfConduct)

### PR Type
What kind of change does this PR introduce?

- [ ] Bug fix
- [ ] Feature
- [X] Chore (refactoring, formatting, local variables, other cleanup)
- [ ] Documentation content changes

### What is the current behavior?

Issue Number: N/A

### Does this PR introduce a breaking change?
- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by amolenaar** [comment]
Looks good. Do you want to merge #3059 first?

**Review by amolenaar — APPROVED** [review]

**Comment by amolenaar** [comment]
The VirusTotal results for this build look more promising: https://www.virustotal.com/gui/file/682aa8b104f2331ca484ac4c35ed2c6153524c11d870ab23b6a71b4e3e792242?nocache=1.

**Comment by danyeaw** [comment]
@amolenaar That does look really nice! Should we try to do a new release soon?

**Comment by amolenaar** [comment]
I'm curious if our resulting installer will be considered free of viruses as well.

**Pull request merged**
