### PR TITLE
Fix macOS shortcuts on GTK 4

### PR DESCRIPTION
**Pull request by amolenaar**
### PR Type
What kind of change does this PR introduce?

- [] Bug fix
- [ ] Feature
- [x] Chore (refactoring, formatting, local variables, other cleanup)
- [ ] Documentation content changes

### What is the current behavior?

On GTK4 no magic mapping is done for us on macOS, where `Command` serves as primary modifier.

Issue Number: #1839

### What is the new behavior?

We remap the `Primary` modifier on macOS to the `Meta` key (`Command`).

image

### CODE REVIEW

**Comment by mathiascode** [comment]
GTK's built-in shortcuts (e.g. Ctrl+C in textviews) would still be a problem, right?

**Review by danyeaw — APPROVED** [review]
Nice improvement for macOS @amolenaar

**Comment by amolenaar** [comment]
> GTK's built-in shortcuts (e.g. Ctrl+C in textviews) would still be a problem, right?

Fair point 🤔. Not sure how easily those can be remapped. It's mainly text views and entry widgets, right? I assume the tab bar has some shortcuts as well.

**Comment by amolenaar** [comment]
I think we can add additional keyboard shortcuts via `Gtk.Widget.add_shortcut()` at class level. The original (`ctrl`-based) keybindings can stay.

**Comment by amolenaar** [comment]
This is the list of supported keybindings on macOS: https://support.apple.com/en-us/HT201236.

**Pull request merged**
