### PR TITLE
Update Style Sheet Editor to be a Code Editor

### PR DESCRIPTION
**Pull request by danyeaw**
Uses GtkSourceView to add CSS syntax highlighting, auto indent, and use spaces instead of tabs.

Signed-off-by: Dan Yeaw <dan@yeaw.me>

### PR Checklist
Please check if your PR fulfills the following requirements:

- [X] I have read, and I am following the [Contributor guide](https://github.com/gaphor/gaphor/blob/master/CONTRIBUTING.md)
- [X] I have read, and I understand the [Code of Conduct](https://github.com/gaphor/gaphor/blob/master/CODE_OF_CONDUCT.md)

### PR Type
What kind of change does this PR introduce?

- [ ] Bug fix
- [X] Feature
- [ ] Chore (refactoring, formatting, local variables, other cleanup)
- [ ] Documentation content changes

### What is the current behavior?
The style sheet editor is a basic text editor with no code editing features.

Issue Number: #804 

### What is the new behavior?
Code editor features are now supported.

### Does this PR introduce a breaking change?
- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by amolenaar** [comment]
GtkSourceView is not (properly) packaged with the macOS installation. I suppose the same goes for the Windows installation.

```
rjan@Arjans-MBP-2:Gaphor.app/Contents $ MacOS/gaphor-exe
Traceback (most recent call last):
  File "gaphor-script.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "gaphor/__init__.py", line 13, in <module>
  File "gi/__init__.py", line 126, in require_version
ValueError: Namespace GtkSource not available
[1629] Failed to execute script 'gaphor-script' due to unhandled exception: Namespace GtkSource not available
[1629] Traceback:
Traceback (most recent call last):
  File "gaphor-script.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "gaphor/__init__.py", line 13, in <module>
  File "gi/__init__.py", line 126, in require_version
ValueError: Namespace GtkSource not available
```

**Comment by danyeaw** [comment]
@amolenaar Thanks, good catch. I'll take a :eyes:.

**Comment by amolenaar** [comment]
I'm still wondering why GtkSourceView is not picked up by PyInstaller. GtkMacIntegration is...

**Comment by danyeaw** [comment]
Replaced by #1029 in order to change branches used.

**Pull request closed without merging**
