### PR TITLE
Improve GTK4 compatibility

### PR DESCRIPTION
**Pull request by amolenaar**
### PR Type
What kind of change does this PR introduce?

- [ ] Bug fix
- [ ] Feature
- [X] Chore (refactoring, formatting, local variables, other cleanup)
- [ ] Documentation content changes

### What is the current behavior?

Gaphor would not start on GTK4 anymore.

Issue Number: #618  

### What is the new behavior?

The app loads. We can add items to the diagram.

PyGObject is hotfixed.

### Does this PR introduce a breaking change?
- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by danyeaw** [comment]
Tumbleweed has gtksoureview5 😎

**Comment by amolenaar** [comment]
> Tumbleweed has gtksoureview5 sunglasses

Oddly enough Fedora 35 does not :disappointed: .

Anyhow, changing it back is very simple. But the really big challenge will be the treeview (a rewrite?) and DnD support.

Windows is currently broken 'cause I'm building against PyGObject master.

**Comment by danyeaw** [comment]
@amolenaar If it helps, I could quickly make a branch of gvsbuild that uses the latest PyGObject from source.

**Comment by amolenaar** [comment]
> @amolenaar If it helps, I could quickly make a branch of gvsbuild that uses the latest PyGObject from source.

@danyeaw I don't think that's needed. We miss quite a few features in GTK4 at the moment (for example DnD on macOS) that it's not feasible to use GTK4 as our default any time soon.

**Comment by amolenaar** [comment]
@danyeaw It has become a mashup of changes. Mostly they favor GTK 3/4 compatibility.

I removed the PyGObject change to a non-released version.

Unit tests work fine, the app starts and works sort of.

**Review by danyeaw — APPROVED** [review]
Nice improvements towards GTK4 :+1:

**Pull request merged**
