### PR TITLE
Allow sequence diagram messages on lifeline body

### PR DESCRIPTION
**Pull request by amolenaar**
### PR Type
What kind of change does this PR introduce?

- [ ] Bug fix
- [x] Feature
- [ ] Chore (refactoring, formatting, local variables, other cleanup)
- [ ] Documentation content changes

### What is the current behavior?

Issue Number: #1599 

### What is the new behavior?

* Messages can be connected everywhere on a lifeline object
* The timeline can now always be extracted (used to be blocked when a message was connected to the body)
* Saving and loading has been fixed to support connecting to body as well as timeline
* Only if a message is connected between two lifeline elements without timeline (timeline is collapsed), a communication diagram style message will be shown.

### Does this PR introduce a breaking change?
- [x] Yes
- [ ] No

Timeline length is saved differently.

### CODE REVIEW

**Comment by danyeaw** [comment]
These updates look good to me. I am not sure if these changes are related to this, but I caught an exception while dragging a message from the timeline back to the lifeline:

```
|Traceback (most recent call last):
|  File "/home/dan/Projects/gaphor/.venv/lib/python3.10/site-packages/gaphas/tool/itemtool.py", line 122, in on_drag_update
|    moving.move((x, y))
|    │            │  └ 221.92576599121094
|    │            └ 385.34375
|    └ <gaphor.diagram.tools.grayout.GrayOutLineHandleMove object at 0x7f6076d5ff70>
|  File "/home/dan/Projects/gaphor/.venv/lib/python3.10/site-packages/gaphas/guide.py", line 241, in move
|    super().move(pos)  # type: ignore[misc]
|                 └ (385.34375, 221.92576599121094)
|  File "/home/dan/Projects/gaphor/.venv/lib/python3.10/site-packages/gaphas/handlemove.py", line 49, in move
|    self.handle.glued = bool(self.glue(pos))
|    │                        │         └ (385.34375, 221.92576599121094)
|    │                        └ <gaphor.diagram.tools.grayout.GrayOutLineHandleMove object at 0x7f6076d5ff70>
|    └ <gaphor.diagram.tools.grayout.GrayOutLineHandleMove object at 0x7f6076d5ff70>
|  File "/home/dan/Projects/gaphor/gaphor/diagram/tools/grayout.py", line 48, in glue
|    sink = super().glue(pos, distance)  # type: ignore[misc]
|                        │    └ 10
|                        └ (385.34375, 221.92576599121094)
|  File "/home/dan/Projects/gaphor/.venv/lib/python3.10/site-packages/gaphas/handlemove.py", line 80, in glue
|    if connector.glue(sink):
|  File "/home/dan/Projects/gaphor/.venv/lib/python3.10/site-packages/gaphas/connector.py", line 56, in glue
|    glue_pos = sink.glue(pos, secondary_pos)
|               │         │    └ (-224.44139862060547, 50.0)
|               │         └ (29.28515625, 39.32421875)
|               └ <gaphas.connector.ElementConnectionSink object at 0x7f6076d6ae30>
|  File "/home/dan/Projects/gaphor/.venv/lib/python3.10/site-packages/gaphas/connector.py", line 174, in glue
|    assert isinstance(p, LinePort)
|                      │  └ <class 'gaphas.port.LinePort'>
|                      └ <gaphor.UML.interactions.lifeline.BetweenPort object at 0x7f602c55dc60>
|AssertionError: assert isinstance(p, LinePort)
```

**Comment by amolenaar** [comment]
@danyeaw Thanks for catching this. It is related to this PR. Since Lifetime has it's own (custom) `BetweenPort`, which is not a `LinePort`.

**Comment by amolenaar** [comment]
> These updates look good to me. I am not sure if these changes are related to this, but I caught an exception while dragging a message from the timeline back to the lifeline:

@danyeaw Fixed :smiley:

**Review by danyeaw — APPROVED** [review]
Nice improvement!

**Pull request merged**
