### PR TITLE
A venv script

### PR DESCRIPTION
**Pull request by amolenaar**
### PR Checklist
Please check if your PR fulfills the following requirements:

- [X] I have read, and am following the [Contributer guide](https://github.com/gaphor/gaphor/blob/master/CONTRIBUTING.md)
- [X] I have read and understand the [Code of Conduct](https://github.com/gaphor/gaphor/blob/master/CODE_OF_CONDUCT.md)

### PR Type
What kind of change does this PR introduce?

- [X] Development support
- [X] Feature

### What is the current behavior?

Currently a newcomer to the project has to figure out how to get Gaphor up and running. It would be helpful if we provide one or two scripts that set up an environment in a controlled way (there are many tools around for installing dependencies and such).

### What is the new behavior?

A script to help you out with a reproducable venv.

### Does this PR introduce a breaking change?
- [ ] Yes
- [X] No

### Other information

- [ ] README still needs an update

### CODE REVIEW

**Comment by amolenaar** [comment]
Ah, that looks fine.

I run into some trouble with the pyproject.toml file though. I'm not sure how to solve it:

```
[UnexpectedCharError]            
Unexpected character: '\n' at line 55 col 21  
```
(https://github.com/gaphor/gaphor/blob/master/pyproject.toml#L55)

What's `testenv` supposed to do?

**Comment by danyeaw** [comment]
@amolenaar I reviewed and tested this on my machine. It looks really good. Should we update the README to tell users who want to setup a development environment need to run `source venv` and launch gaphor with `gaphor`?

**Comment by amolenaar** [comment]
@danyeaw Thanks. Good to hear it "works on your machine" to :)  I'll update the readme.

**Comment by danyeaw** [comment]
Nice one :heart:

**Pull request merged**
