### PR TITLE
Build a development Flatpak

### PR DESCRIPTION
**Pull request by amolenaar**
### PR Type
What kind of change does this PR introduce?

- [ ] Bug fix
- [x] Feature
- [ ] Chore (refactoring, formatting, local variables, other cleanup)
- [ ] Documentation content changes

### What is the current behavior?

Make it easy to build and test Gaphor as a Flatpak.

This build should not be confused for the release build, which is created by https://github.com/flathub/org.gaphor.Gaphor

Issue Number: #1840 

### What is the new behavior?

You can build a flatpak more easily.

@bertob I added a simple flatpak script in the root folder. It's using a "simple" build system and the local directory. I can build the flatpak with the right commands:

```
flatpak-builder build --force-clean --install --user org.gaphor.Gaphor.yaml
flatpak run -d org.gaphor.Gaphor
```
I was not able to figure out how Builder should build and run the application.

### CODE REVIEW

**Review by danyeaw — APPROVED** [review]
This looks great to me. @bertob does this meet what you were looking for?

**Comment by bertob** [comment]
Manifest in the project root should work, but AFAIK yaml manifests don't work in Builder, so it'd need to be json for the one-click build to work.

**Comment by amolenaar** [comment]
JSON it is, then :). Indeed I noticed that Builder recognizes the flatpak file instantly.

**Comment by danyeaw** [comment]
Nice!

**Pull request merged**
