### PR TITLE
Replace deprecated Gtk.FileChooser by FileDialog

### PR DESCRIPTION
**Pull request by amolenaar**
### PR Type
What kind of change does this PR introduce?

- [ ] Bug fix
- [ ] Feature
- [x] Chore (refactoring, formatting, local variables, other cleanup)
- [ ] Documentation content changes

### What is the current behavior?

Issue Number: #2231 

### What is the new behavior?

Use the modern `FileDialog` API.

### Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### Other information

Not sure if it's still using the native dialogs on Windows and macOS.

`Gtk.FileDialog` is introduced in GTK 4.10. ~We're still building on 4.6 (Ubuntu 22.04). 
I think we can wait until we have GTK 4.10+ available on our build machines.~

### CODE REVIEW

**Comment by danyeaw** [comment]
I wonder if we could use the flatpak environment to run the test suite :thinking:

**Comment by amolenaar** [comment]
It would still be good to build it on a normal machine. We could use a Fedor container, but that would pose other challenges.

**Comment by danyeaw** [comment]
Hi @amolenaar, I went to Save As, then clicked Cancel and got the following traceback:

```
Traceback (most recent call last):
  File "/home/dan/Projects/gaphor/gaphor/ui/filedialog.py", line 85, in response
    filename = Path(dialog.save_finish(result).get_path())
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: gtk-dialog-error-quark: Dismissed by user (2)
```

**Comment by amolenaar** [comment]
@danyeaw Fixed the issue with the cancel button.

**Comment by danyeaw** [comment]
@amolenaar Do you know why these tests are failing?

**Comment by amolenaar** [comment]
Sorry, I should've run them before I committed 😨 .

**Review by danyeaw — APPROVED** [review]
Thanks @amolenaar, this is a great upgrade!

**Pull request merged**
