### PR TITLE
Add Support for SysML and Safety & Reliability Analysis Profile

### PR DESCRIPTION
**Pull request by danyeaw**
Adds the ability to select a modeling profile beyond UML. Adds support for SysML 1.6 and the soon to be released Safety and Reliability Analysis Profile 1.0.

### PR Checklist
Please check if your PR fulfills the following requirements:

- [X] I have read, and am following the [Contributer guide](https://github.com/gaphor/gaphor/blob/master/CONTRIBUTING.md)
- [X] I have read and understand the [Code of Conduct](https://github.com/gaphor/gaphor/blob/master/CODE_OF_CONDUCT.md)

### PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes

Issue Number: #138 

### Does this PR introduce a breaking change?
- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by danyeaw** [comment]
The current UML profile capabilities does not include the <<import>> or <<apply>> dependencies which are part of the UML spec. In order to tell the model to import, for example UML, my plan is to add this dependency. The most general use case of this would be to allow users to import any gaphor model through a file selection dialog. What we need for being able to add the SysML and Safety & Reliability Profiles is only to import the UML and SysML profiles themselves. I think for this use case we can just import the profile through searching for a model with the package name. Any thoughts on this approach?

**Comment by amolenaar** [comment]
Import and apply dependency sounds like a good plan. If all models are found in a `gaphor.models` module (UML too) we can just do a simple "import" for the dependent model entry. Or use the overrides file, but that's less fancy. I do not think the UML model needs to be treated any different from the SysML models.

I would not use a "cold" module lookup. That will inhibit us from doing any changes to Gaphor's structure. Maybe a module where all metamodels come together so we can select from there?

**Comment by danyeaw** [comment]
@amolenaar I like the idea to put everything in `gaphor.models`. Can you explain more what you mean by a cold module lookup?

**Comment by amolenaar** [comment]
I think I was thinking about loading and saving models. I think we want a level of indirection between how it's saved and how it's discoverable in Gaphor.

**Comment by danyeaw** [comment]
## Status

Currently I am able to draw the import relationship on a diagram, and constrain the dependency between Packages. The relationship is also successfully saving in the gaphor file format, since the UML data model already had support for this.

## Design Thoughts on Referencing Across Profiles

If we want, for example, the SysML profile to define an element as an extension of a Class, I think we need to reference the Class using either the Gaphor models or the generated data models.
For the Gaphor models, the SysML profile needs to use the same ref-id as the one in the UML Gaphor model. If we use reference them using the data model, then we can look for an element called Class in the UML data model. 

One advantage of referencing the elements using the Gaphor models is this might be a nice Feature to allow any model to import another model for reusability. This Import Model option could be placed in the hamburger menu. If we were to do this, then I think the cleanest approach would be to create a new tag in the file format to reference another model. Then when that model is loading it loads the other model as well. There are ways this starts to get complicated:
1. Do we reference the other model from a relative or absolute path?
2. What happens if the referenced model can't be found? Do we then have to bring up a dialog to ask the user to select the updated location?

On the other hand, I think referencing the elements in the data model may be simpler. Especially if we use the import relationship, then we can use that to search for elements of the same name in the namespace we are adding. I do need to dig in to this a bit more.

Any other thoughts or comments on the best method to implement this?

**Comment by danyeaw** [comment]
Breaking this up in to multiple more manageable PRs.

**Pull request closed without merging**
