### PR TITLE
Assign activities to classifiers

### PR DESCRIPTION
**Pull request by amolenaar**
### PR Type
What kind of change does this PR introduce?

- [ ] Bug fix
- [x] Feature
- [ ] Chore (refactoring, formatting, local variables, other cleanup)
- [ ] Documentation content changes

### What is the new behavior?

Activities (behaviors) can now be nested in classifier elements. This allows for an ARCADIA style of modeling.

### Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### Other information

Update `vertical-align` in items to `justify-content`. Also checked if all items properly move their name if they get a child item.

### CODE REVIEW

**Comment by danyeaw** [comment]
I am not very familiar with ARCADIA since it is so tightly coupled with Capella. Does UML and SysML allow for an activity to be nested in a Classifier? I am use to this behavior to structure relationship being created through creating swimlanes, assigning a Classifier to each swimlane, and putting the activities in the swimlanes.

**Comment by amolenaar** [comment]
There is an ownership relation between the behavior and the classifier.

image

I made it available as a grouping options, which allows you to assign activities to those elements, either in the tree view or in a diagram. The ownership is indeed valid according to UML.

Most of my exposure to ARCADIA is on the functional level, where you assign activities to certain classifiers. Quite superficial I suppose.

**Comment by danyeaw** [comment]
Not disagreeing, just want to make sure we get this right.

With other tools, if you add an activity to a Class Diagram or Block Definition Diagram it is represented like this with ownership:

image

If you drop an activity on a block, it adds an attribute:
image

Here's the tree view:

image

**Comment by amolenaar** [comment]
I see. It's a bit odd to assign an activity and present it as a property, though.

Containment also works in this case. I updated the containment connection code to use our "group" feature.

image

**Review by danyeaw — APPROVED** [review]
Looks good!

**Pull request merged**
