### PR TITLE
Russian translation updates

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Gaphor/Gaphor](https://hosted.weblate.org/projects/gaphor/gaphor/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by danyeaw** [comment]
Thanks @BrainKicker!

**Comment by BrainKicker** [comment]
> Thanks @BrainKicker!

Hi. You are welcome!

I have some questions about translation:
1) What is the purpose of string "_Open"? Is it a verb or an adjective? Should I translate it?
2) What is the transcription of your last name?

**Comment by danyeaw** [comment]
Hi @BrainKicker!

Anything with an underscore is menu action and the underscore sets the keyboard shortcut. I think generally menu actions are verbs. For example, Open is to Open a Model.

I don't think we should be translating names.

**Comment by BrainKicker** [comment]
So does underscore play some role in the work of the program?
Because I haven't found any of these strings anywhere in the program.
Maybe they're displayed without underscore?

**Comment by danyeaw** [comment]
They should, I would expect that the O would be underlined here:
image

This could be a bug, or maybe a bug in Windows - I only have access to a Windows computer at the moment. @amolenaar the underscores set the keyboard shortcuts correct?

**Comment by BrainKicker** [comment]
The context menu blocks my screenshot program for some reason, but on my Linux Mint Vera 21.1 Flatpak Gaphor also doesn't underline "O".

Also, as I assume, this underscore should related to a keyboard shortcut, but if I translate the string, it won't have the English "O" (the corresponding letter on Russian keyboard) in it.
So I don't quite understand where I should put the underscore.
Maybe I should get rid of it?

**Pull request merged**
