### PR TITLE
Add ownership rules to DirectedRelationshipPropertyPath.targetContext

### LINKED ISSUE #2621: Trace (and derived relationships) show up at the top model level
### Describe the bug
Trace relationships (trace, derive, refine, satisfy, and verify) show up at the top level of the model instead of under their supplier block (or supplier block containing folder). 

### To Reproduce
1. Create 2 requirement blocks
2. add a derive relationship

### Expected behavior
I'd expect the relationships to appear under the supplier block similar to associations. 

### OS
- [ ] Linux (Please put in notes the specific distro)
- [X] macOS
- [ ] Windows

### Version
Version of Gaphor: 2.20.0

### PR DESCRIPTION
**Pull request by amolenaar**
### PR Type
What kind of change does this PR introduce?

- [x] Bug fix
- [ ] Feature
- [ ] Chore (refactoring, formatting, local variables, other cleanup)
- [ ] Documentation content changes

### What is the current behavior?

Relationships like Trace, DeriveReqt end up in the Model  Browser root.

Issue Number: fixes #2621 

### What is the new behavior?

This fixes those requirement relations to end up in the root of the model.

Screenshot from 2023-08-17 22-12-15

### Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### Other information

Not sure if we want this relationship on the source or target side. I choose target for now.

I also added a format function (not shown on screenshot).

### CODE REVIEW

**Comment by danyeaw** [comment]
Hi @amolenaar, this is a nice feature!

Should we add a watch to the sourceContext.name so that it updates immediately in the Model Browser when the name of the Requirement changes?

**Comment by amolenaar** [comment]
Good point. I'll look into it.

**Comment by amolenaar** [comment]
Ehhmm... We do not have that in place currently. Renames are not updated for normal names even.

**Comment by amolenaar** [comment]
I created #2657 for this issue.

**Review by danyeaw — APPROVED** [review]
Thanks @amolenaar!

**Pull request merged**
