### PR TITLE
Add hint for button to edit CSS in style_sheet.md

### PR DESCRIPTION
**Pull request by Holzhauer**
### PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I have read, and I am following the [Contributor guide](https://github.com/gaphor/gaphor/blob/main/CONTRIBUTING.md)
- [x] I have read, and I understand the [Code of Conduct](https://github.com/gaphor/gaphor/blob/main/CODE_OF_CONDUCT.md)

### PR Type
What kind of change does this PR introduce?

- [ ] Bug fix
- [ ] Feature
- [ ] Chore (refactoring, formatting, local variables, other cleanup)
- [x] Documentation content changes

### What is the current behavior?
Students in my course struggle to find the input field for CSS code. This hint should help.

Issue Number: N/A

### Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### Other information
-

### CODE REVIEW

**Comment by amolenaar** [comment]
Hi @Holzhauer,

Thank you. This is much appreciated. Something broke the documentation generation on the main branch, so I wanted to fix that before merging your PR.

@all-contributors add @Holzhauer for docs

**Comment by danyeaw** [comment]
@Holzhauer at of curiosity, which University Course are you using Gaphor for?

**Comment by Holzhauer** [comment]
@danyeaw I use gaphor in an introduction course to agent-based modelling (ABM). UML class and activity diagrams are convenient ways to document ABM models, and I was looking for a light-weight python-based UML editor.

**Comment by danyeaw** [comment]
Great @Holzhauer! It is always interesting to hear about how people are using Gaphor, thanks for sharing.

**Pull request merged**
