### PR TITLE
Dependency updates

### PR DESCRIPTION
**Pull request by mrmonkington**
This PR:

  - Adds `sphinxcontrib-images` to dev deps so that documentation will build
  - Set min python version to 3.9 since master is now incompatible with earlier versions

I am unsure if this will break packaging.

### PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I have read, and I am following the [Contributor guide](https://github.com/gaphor/gaphor/blob/master/CONTRIBUTING.md)
- [x] I have read, and I understand the [Code of Conduct](https://github.com/gaphor/gaphor/blob/master/CODE_OF_CONDUCT.md)

### PR Type
What kind of change does this PR introduce?

- [x] Bug fix
- [ ] Feature
- [ ] Chore (refactoring, formatting, local variables, other cleanup)
- [ ] Documentation content changes

### What is the current behavior?

Currently, poetry runs no checks against the current/active python version, and (almost) out-of-box new contributor experience on Ubuntu 20.04 is that tests fail as a result.

Issue Number: N/A

### What is the new behavior?

Poetry will attempt to activate correct pyenv or fail.

### Does this PR introduce a breaking change?
- [x] Yes *possibly*
- [ ] No

### CODE REVIEW

**Review by danyeaw — CHANGES_REQUESTED** [review]
Hi @mrmonkington, really nice additions and congrats on your first PR! :balloon: 

So that the next person is able to make use of these updates, could you please run `poetry update`? That will update the `poetry.lock` file with your modifications. Thanks!

**Comment by danyeaw** [comment]
@all-contributors please add @mrmonkington for code and bug

**Comment by danyeaw** [comment]
@mrmonkington Thanks again for the PR, are you interested in fixing up the last part so that we can merge this?

**Comment by mrmonkington** [comment]
Apologies - took a few days off!

**Comment by danyeaw** [comment]
@mrmonkington Thanks! 🎉

**Pull request merged**
