### PR TITLE
Add GTK4 build on macos

### PR DESCRIPTION
**Pull request by amolenaar**
On macOS it's easier to install GTK4 than on Ubuntu ;)

### CODE REVIEW

**Comment by amolenaar** [comment]
PyGObject [needs an update](https://gitlab.gnome.org/GNOME/pygobject/-/merge_requests/172)

**Comment by danyeaw** [comment]
It is too bad that GitHub Actions doesn't allow for an allow-failure option for some builds, we don't want the other builds to cancel or the overall status to show as failed if GTK4 fails.

**Comment by amolenaar** [comment]
Excellent suggestion! There is such an option :smiley:.

**Comment by danyeaw** [comment]
Nice one!

**Pull request merged**
