### PR TITLE
Update gif file in Gaphor

### PR DESCRIPTION
**Pull request by seryafarma**
Update the gif in the docs of Gaphor. The same sequence of usage is done in this new gif in comparison with the previous one.

### PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I have read, and am following the [Contributer guide](https://github.com/gaphor/gaphor/blob/master/CONTRIBUTING.md)
- [x] I have read and understand the [Code of Conduct](https://github.com/gaphor/gaphor/blob/master/CODE_OF_CONDUCT.md)

### PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Documentation content changes

### What is the current behavior?

Issue Number: #329 

### What is the new behavior?
New gif based on the latest version of Gaphor.

### Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### Other information
Please give inputs whether there is any improvement points I can further make in the gif.

### CODE REVIEW

**Comment by danyeaw** [comment]
@seryafarma Thanks so much for the contribution!

Is this gif from Elementary OS? Although I have installed that distribution before to check it out, I haven't actually seen Gaphor running on it before, so that is cool. :+1: 

One thing that I noticed is that the updated inline editor using the Gtk.Entry isn't showing up like it does in GNOME:
image

That might be a bug. Is this the latest version from source or did you download a released version?

**Comment by seryafarma** [comment]
Hi Danyeaw, I am actually using my zorinos laptop for making that gif. Do you need a specific gif based on a specific distro?

I installed Gaphor using flatpak as mentioned in the readme.

**Comment by seryafarma** [comment]
I will make another gif file using my linux mint. It seems like gaphor shows the same inline update textbox when I use mint. Thanks for the input! Will update this PR.

**Comment by danyeaw** [comment]
@seryafarma That looks great, thanks again for the great contribution! :tada:

**Comment by amolenaar** [comment]
@seryafarma Thanks a lot :rocket:

**Pull request merged**
