### PR TITLE
Direct association

### PR DESCRIPTION
**Pull request by sz332**
### PR Checklist
Please check if your PR fulfills the following requirements:

- [X] I have read, and I am following the [Contributor guide](https://github.com/gaphor/gaphor/blob/main/CONTRIBUTING.md)
- [X] I have read, and I understand the GNOME [Code of Conduct](https://wiki.gnome.org/Foundation/CodeOfConduct)

### PR Type
Direct association between classes and sysml blocks.

- [ ] Bug fix
- [X] Feature
- [ ] Chore (refactoring, formatting, local variables, other cleanup)
- [ ] Documentation content changes

### What is the current behavior?

Currently it is very painful to create a direct (navigable) association. A normal association must be created, then going into properties, finding the tail element, and setting navigability. It takes just too much time.

Issue Number: 2516

### What is the new behavior?

A new toolbar button is added enabling the same outcome with a single click. 

### Does this PR introduce a breaking change?
- [ ] Yes
- [X] No

### Other information

I could not find how to properly do the translations so I need some help in that.

### CODE REVIEW

**Comment by amolenaar** [comment]
@sz332 This looks good. Is it ready to merge?

**Comment by sz332** [comment]
> @sz332 This looks good. Is it ready to merge?

It is ready to merge, the one think I don't know how to do is translation. Should I do something, or is it a separate process? If I need to do something, can you please help me to add the necessary translation string?

**Comment by amolenaar** [comment]
Translation is something we kick of separately mostly, so we can update all text in one shot.

**Review by amolenaar — APPROVED** [review]

**Comment by amolenaar** [comment]
@sz332 The unit tests fail with a message:

```
Duplicate toolbox shortcut <Shift>O for ['toolbox-direct-association', 'toolbox-object-node']
```

I think the keyboard shortcut should be removed from directed-association. It can be `None`.

**Comment by sz332** [comment]
> @sz332 The unit tests fail with a message:
> 
> ```
> Duplicate toolbox shortcut <Shift>O for ['toolbox-direct-association', 'toolbox-object-node']
> ```
> 
> I think the keyboard shortcut should be removed from directed-association. It can be `None`.

Removed the keyboard shortcuts. Can you try it out? Thanks!

**Pull request merged**
