### PR TITLE
Add Slovenian Translation

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Gaphor/Gaphor](https://hosted.weblate.org/projects/gaphor/gaphor/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by danyeaw** [comment]
@all-contributors please add @perovsek for translation

**Comment by danyeaw** [comment]
Thanks @perovsek!

**Comment by perovsek** [comment]
Thank you!

So I only started with the translation, it's by no means finished. 

I am curious about how the process works. Does this merge mean that the contents will be updated automatically when new translated strings are being added or is there a need for a separate merge every time?

I want to consult the Fran Ramovš Institute of the Slovenian Language regarding how correct some translations are because I don't want to translate academic language in a naive way.

However, I don't think it's such a problem if a half-finished translation is available before this is done, at least before SysML 2.0 comes along or some bigger update of Gaphor is released.

**Comment by danyeaw** [comment]
@perovsek Once translations are updated and merged, as soon as we release a new version they will be available to users with Slovenian language selected in their environment. If a string isn't translated, then it will show up in English.

**Pull request merged**
