### PR TITLE
Prepare for version 2.23.1 release

### PR DESCRIPTION
**Pull request by danyeaw**
Bumps the version and updates the changelog.

### PR Checklist
Please check if your PR fulfills the following requirements:

- [X] I have read, and I am following the [Contributor guide](https://github.com/gaphor/gaphor/blob/main/CONTRIBUTING.md)
- [X] I have read, and I understand the GNOME [Code of Conduct](https://wiki.gnome.org/Foundation/CodeOfConduct)

### PR Type
What kind of change does this PR introduce?

- [ ] Bug fix
- [ ] Feature
- [X] Chore (refactoring, formatting, local variables, other cleanup)
- [ ] Documentation content changes

### What is the current behavior?

Issue Number: N/A

### Does this PR introduce a breaking change?
- [ ] Yes
- [X] No

### CODE REVIEW

**Review by amolenaar — APPROVED** [review]
Nice!

**Comment by amolenaar** [comment]
What happened to the build? The lint job seems to fail 'cause it cannot find the python binary (?)

**Comment by danyeaw** [comment]
I'm not sure either, it also seems flaky as well because if I rerun the build it tends to pass.

**Comment by danyeaw** [comment]
It looks like this issue: https://github.com/pypa/pipx/issues/1195

**Pull request merged**
