### PR TITLE
Stm trigger action

### PR DESCRIPTION
**Pull request by ghillebrand**
Adds `trigger` and `action` to a State Transition Models, in addition to `guard`, as per Issue [#2845](https://github.com/gaphor/gaphor/issues/2845)
trigger and action associations have been added to the UML model Transition Class Diagram , and the code updated to edit and display these attributes as `trigger [guard] /action`

### PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I have read, and I am following the [Contributor guide](https://github.com/gaphor/gaphor/blob/main/CONTRIBUTING.md)
- [x] I have read, and I understand the GNOME [Code of Conduct](https://conduct.gnome.org/)

### PR Type
What kind of change does this PR introduce?

- [ ] Bug fix
- [x] Feature
- [ ] Chore (refactoring, formatting, local variables, other cleanup)
- [ ] Documentation content changes

### What is the current behavior?

Currently, only `guard` text can be entered, which is displayed below the transition as `[guard]`. 
Issue Number: [#2845](https://github.com/gaphor/gaphor/issues/2845)

### What is the new behavior?
Now `trigger` and `action` can independently be entered in the properties dialog, and are displayed according to the UML spec `trigger[guard]/action` on the transition. The text is _below_ the transition, rather than above, which seems to be the UML preference for this.

### Does this PR introduce a breaking change?
- [x] Yes
- [ ] No

This does not seem to be backwards compatible - models created with these changes do not open in older versions of gaphor. This seems to be related to the file loading code. On trying to open a model created with these changes, gaphor (2.25.1 under windows) does nothing - no error, no crash, no model or diagram displayed. 

### Other information
My first PR/ change, so if I have omitted/ mangled something, my apologies!

### CODE REVIEW

**Comment by amolenaar** [comment]
Hi @ghillebrand,

You're definitely on the right track. The code looks okay. To fix the mypy issue, I moved some code around.

Some other changes:

* Merged the code with the main branch. The `@transactional` has been deleted and the UML model had been updated.
* Fixed a small issue in the model, where 2 relations referred to the same association end on behavior.
* I moved the generation of the trigger/guard/action name to a separate method. I think that makes it somewhat more readable.

I was wondering if trigger and action should actually refer to exiting behaviors, such as a activity, state machine, and Interaction. Currently it's creating a new "Behavior" instance, with no relation to the rest of the model (Behavior should have been an abstract class in the model).

**Comment by ghillebrand** [comment]
Thank you :) That all makes sense. 

ITO the behaviour issue, the OP was happy if the trigger-guard-action could be displayed "properly", without too much methodology behind it. I certainly don't know/ use UML enough to begin to make a call on that! 
If you can point me at how to make the text appear _above_ the line, I would happily add that. I would like to understand the drawing side of gaphor better, and that would then meet all the of OP's requirements as I understand them.

My goal is to create a new model type, higraph, which would heavily re-use the STM code, and this was an excellent project to get my head around how the bits of gaphor interact. I should open a feature request, yes? I will outline the steps as I see them, and be guided by you guys on how/ where to implement the various parts.

**Comment by amolenaar** [comment]
@ghillebrand 

You refer to this?

image

The text positioning is mostly done automatic. The `LinePresentation` class initiates text placement and calls [`text_point_at_line`](https://github.com/gaphor/gaphor/blob/main/gaphor/diagram/text.py#L120), which will place the text close to the begin/center/end of the line. The position is dependent on the angle of the respected line segment.

Text placement is the same for all lines/vertices.

**Comment by amolenaar** [comment]
This PR looks good. So I'll merge it.

**Comment by ghillebrand** [comment]
> @ghillebrand
> 
> You refer to this?
> image
> 
> The text positioning is mostly done automatic. The `LinePresentation` class initiates text placement and calls [`text_point_at_line`](https://github.com/gaphor/gaphor/blob/main/gaphor/diagram/text.py#L120), which will place the text close to the begin/center/end of the line. The position is dependent on the angle of the respected line segment.
> 
> Text placement is the same for all lines/vertices.

Yes, this is what I meant, and this looks like the code I was looking for. The OP, and other tools, write the text above the line. When I get a chance, I will play with the hinting values, and see how they behave/ influence things. Controlling text position I would like to be able to do for higraphs.

**Pull request merged**
